public class Inheritance2 EXTENDS Inheritance1
{
Public Void SUB()
 {
     Integer A=50,B=60,R;
     R=A-B;
     System.debug('The Subtraction is :'+r);
     
     ADD();
 }
    
Public Void Moreinfo()
    {
        System.debug(Grandmother);
        System.debug(mothername);
       // System.debug(LoverName); PRIVATE VARIABLE
       Abc();
      	//MyDairy(); PRIVATE METHOD
      	
     }
    
    
    
    
}