GLOBAL VIRTUAL class Inheritance1 
{
    Global String Grandmother ='Vimla';
    Public String MotherName='Kamala';
    Private String LoverName='Mohini';
    
 Global Void ABC()
 {
     System.debug('I am your father');    
 }
    
 Private Void MyDiary()
 {
     System.debug('Secret Stories');
 }
 Public Void ADD()
 {
     Integer A=50,B=60,R;
     R=A+B;
     System.debug('The Addition is :'+r);
 }
}